# Generated by Django 4.2.1 on 2023-05-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
